siganushka_api_factory:
    github:
        client_id: '%env(string:GITHUB_CLIENT_ID)%'
        client_secret: '%env(string:GITHUB_CLIENT_SECRET)%'
    wechat:
        default_configuration: miniapp
        configurations:
            mp:
                appid: '%env(string:WECHAT_MP_APPID)%'
                secret: '%env(string:WECHAT_MP_SECRET)%'
            open:
                appid: '%env(string:WECHAT_OPEN_APPID)%'
                secret: '%env(string:WECHAT_OPEN_SECRET)%'
            miniapp: 
                appid: '%env(string:WECHAT_MINIAPP_APPID)%'
                secret: '%env(string:WECHAT_MINIAPP_SECRET)%'
    wxpay:
        appid: '%env(string:WXPAY_APPID)%'
        mchid: '%env(string:WXPAY_MCHID)%'
        mchkey: '%env(string:WXPAY_MCHKEY)%'
        mch_client_cert: '%env(resolve:WXPAY_MCH_CLIENT_CERT)%'
        mch_client_key: '%env(resolve:WXPAY_MCH_CLIENT_KEY)%'
    alipay:
        appid: '%env(string:ALIPAY_APPID)%'
        app_private_key: '%env(string:ALIPAY_APP_PRIVATE_KEY)%'
        alipay_public_key: '%env(string:ALIPAY_ALIPAY_PUBLIC_KEY)%'
