twig:
    file_name_pattern: '*.twig'
    form_themes:
        - bootstrap_5_horizontal_layout.html.twig
        - '@SiganushkaGeneric/form_div_layout.html.twig'

when@test:
    twig:
        strict_variables: true
