framework:
    workflows:
        order_state:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: method
                property: stateAsString
            supports: Siganushka\OrderBundle\Entity\Order
            transitions:
                pay:
                    from: placed
                    to: accepted
                delivery:
                    from: accepted
                    to: delivered
                receive:
                    from: delivered
                    to: finished
                refund:
                    from: accepted
                    to: refunded
                cancel:
                    from: placed
                    to: cancelled
                reset:
                    from: [accepted, delivered, finished, refunded, cancelled]
                    to: placed
