framework:
    workflows:
        order_state:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: method
                property: stateAsString
            supports: Siganushka\OrderBundle\Entity\Order
            transitions:
                pay:
                    from: placed
                    to: confirmed
                ship:
                    from: confirmed
                    to: shipped
                receive:
                    from: shipped
                    to: finished
                refund:
                    from: [confirmed, finished]
                    to: refunded
                cancel:
                    from: placed
                    to: cancelled
                reset:
                    from: [confirmed, shipped, finished, refunded, cancelled]
                    to: placed
