App\Entity\Goods:
    attributes:
        id:
            groups: ['goods:item', 'goods:collection']
        title:
            groups: ['goods:item', 'goods:collection']
        subtitle:
            groups: ['goods:item', 'goods:collection']
        cover:
            groups: ['goods:item', 'goods:collection']
        price:
            groups: ['goods:item', 'goods:collection']
        stock:
            groups: ['goods:item', 'goods:collection']
