App\Entity\Topup:
    attributes:
        id:
            groups: []
        title:
            groups: []
        amount:
            groups: []
        transactions:
            groups: []
        createdAt:
            groups: []
        updatedAt:
            groups: []
