App\Entity\PaymentOrder:
    attributes:
        id:
            groups: []
        order:
            groups: []
        number:
            groups: [payment.item, payment.collection, 'order:item', 'order:collection']
        amount:
            groups: [payment.item, payment.collection, 'order:item', 'order:collection']
        refundAmount:
            groups: [payment.item, payment.collection, 'order:item', 'order:collection']
        currency:
            groups: [payment.item, payment.collection, 'order:item', 'order:collection']
        gateway:
            groups: [payment.item, payment.collection, 'order:item', 'order:collection']
        details:
            groups: []
        state:
            groups: [payment.item, payment.collection, 'order:item', 'order:collection']
        failedReason:
            groups: [payment.item, payment.collection, 'order:item', 'order:collection']
        refunds:
            groups: []
        titleParameters:
            groups: []
        title:
            groups: [payment.item, payment.collection, 'order:item', 'order:collection']
        type:
            groups: [payment.item, payment.collection, 'order:item', 'order:collection']
        refundableAmount:
            groups: [payment.item, payment.collection, 'order:item', 'order:collection']
        createdAt:
            groups: [payment.item, payment.collection, 'order:item', 'order:collection']
        updatedAt:
            groups: [payment.item, payment.collection, 'order:item', 'order:collection']
        expiredAt:
            groups: [payment.item, payment.collection]
