App\Entity\Topup:
    attributes:
        id:
            groups: [topup.item, topup.collection, 'topup:collection']
        title:
            groups: [topup.item, topup.collection]
        amount:
            groups: [topup.item, topup.collection]
        payments:
            groups: []
        createdAt:
            groups: [topup.item, topup.collection]
        updatedAt:
            groups: [topup.item, topup.collection]
