App\Entity\TransactionOrderAggregate:
    attributes:
        id:
            groups: []
        orders:
            groups: []
        number:
            groups: [transaction.item, transaction.collection]
        amount:
            groups: [transaction.item, transaction.collection]
        gateway:
            groups: [transaction.item, transaction.collection]
        details:
            groups: [transaction.item, transaction.collection]
        state:
            groups: [transaction.item, transaction.collection]
        expiredAt:
            groups: [transaction.item, transaction.collection]
        type:
            groups: [transaction.item, transaction.collection]
        expired:
            groups: [transaction.item, transaction.collection]
        createdAt:
            groups: [transaction.item, transaction.collection]
        updatedAt:
            groups: [transaction.item, transaction.collection]
