Siganushka\PaymentBundle\Entity\PaymentRefund:
    attributes:
        id:
            groups: []
        payment:
            groups: []
        number:
            groups: [payment.item, payment.collection, payment_refund.item, payment_refund.collection]
        amount:
            groups: [payment.item, payment.collection, payment_refund.item, payment_refund.collection]
        details:
            groups: []
        successful:
            groups: [payment.item, payment.collection, payment_refund.item, payment_refund.collection]
        failedReason:
            groups: [payment.item, payment.collection, payment_refund.item, payment_refund.collection]
        note:
            groups: [payment.item, payment.collection, payment_refund.item, payment_refund.collection]
        createdAt:
            groups: [payment.item, payment.collection, payment_refund.item, payment_refund.collection]
        updatedAt:
            groups: [payment.item, payment.collection, payment_refund.item, payment_refund.collection]
