Siganushka\ProductBundle\Entity\ProductVariant:
    attributes:
        id:
            groups: ['order:item', 'order:collection']
        price:
            groups: ['order:item', 'order:collection']
        inventory:
            groups: ['order:item', 'order:collection']
        img:
            groups: ['order:item', 'order:collection']
        name:
            groups: ['order:item', 'order:collection']
        outOfStock:
            groups: ['order:item', 'order:collection']
        enabled:
            groups: ['order:item', 'order:collection']
